[project]
name = "neuroadventure" 
version = "0.1.0"

[build-system]
requires = ["setuptools>=73.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["child_chat"]
[tool.setuptools.package-dir]
"child_chat" = "graph/child_chat"